name: agro_hack23
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  async: ^2.11.0
  auto_route: ^7.8.4
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.1.2
  flutter_svg: ^2.0.9
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  nfc_manager: ^3.3.0
  package_info_plus: ^4.2.0
  provider: ^6.0.5
  secure_shared_preferences: ^0.0.4
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  table_calendar: ^3.0.9
  url_launcher: ^6.2.1
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   
    - assets/icon/
    - assets/images/
  


  fonts:
    - family: SF Pro-Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600

    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700
    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/IconServices.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
